version: '3.10.11'
services:
  app:
    build: .
    volumes:
      - .:/cloud
    ports: 
      - "8000:8000"
    image: app:cloud
    container_name: cloud_container
    command: python manage.py runserver 0.0.0.0:8000
   